"""Why this product, in plain English.

Every line is computed from a value in the data. Nothing here is generated by a
language model, which is a deliberate constraint rather than a limitation: an
LLM asked to justify a recommendation will happily invent that a serum is
"clinically proven to reduce redness in two weeks". A template filled from a
column cannot, and a beauty recommendation that lies about a product's claims is
worse than no recommendation.

The `Evidence.supported` flag carries most of the honesty. A checklist that only
ever showed ticks would be marketing; showing the unmet criteria is what makes
the met ones worth reading. And `detail` carries the sample size behind any
statistic, so a claim can always be weighed by the person reading it.
"""

from __future__ import annotations

import pandas as pd

from .schema import (
    MIN_COHORT_FOR_CLAIM,
    POSITIVE_RATING,
    CONCERNS_BY_SLUG,
    Evidence,
    ProductCols,
    Query,
    ReviewCols,
    Scored,
)
from . import rules

INGREDIENT_HIGHLIGHTS = (
    "Hyaluronic Acid",
    "Vitamin C",
    "Niacinamide",
    "Retinol",
    "Salicylic Acid",
    "AHA/Glycolic Acid",
    "Lactic Acid",
    "Collagen",
    "SPF",
)
"""Highlight tokens worth surfacing by name. A user who asked about acne cares
that a product contains salicylic acid; they do not care that it is vegan."""


def build_cohort_stats(reviews: pd.DataFrame) -> pd.DataFrame:
    """Per (product, skin type): how many reviews, and how many were positive.

    Precomputed because the deployed app must never load 1.09M reviews to
    answer one request. Small enough to commit: a few tens of thousands of rows.
    """
    frame = reviews.dropna(subset=[ReviewCols.SKIN_TYPE])
    grouped = frame.groupby([ReviewCols.ITEM, ReviewCols.SKIN_TYPE])
    stats = grouped[ReviewCols.RATING].agg(
        n_reviews="size",
        n_positive=lambda s: int((s >= POSITIVE_RATING).sum()),
    )
    return stats.reset_index()


class Explainer:
    """Turns a `Scored` result into the evidence lines the UI renders."""

    def __init__(
        self,
        products: pd.DataFrame,
        cohort_stats: pd.DataFrame | None = None,
        *,
        min_cohort: int = MIN_COHORT_FOR_CLAIM,
    ) -> None:
        self.products = products.set_index(ProductCols.ID, drop=False)
        self.min_cohort = min_cohort
        self._irritants = rules.build_irritant_flags(products)

        if cohort_stats is not None and len(cohort_stats):
            self.cohort_stats = cohort_stats.set_index(
                [ReviewCols.ITEM, ReviewCols.SKIN_TYPE]
            )
        else:
            self.cohort_stats = None

    # ------------------------------------------------------------------

    def explain(self, scored: Scored, query: Query) -> list[Evidence]:
        if scored.product_id not in self.products.index:
            return []
        product = self.products.loc[scored.product_id]
        evidence: list[Evidence] = []

        cohort = self._cohort_evidence(scored.product_id, query)
        if cohort:
            evidence.append(cohort)

        evidence.extend(self._skin_type_evidence(product, query))
        evidence.extend(self._concern_evidence(product, query))
        evidence.extend(self._ingredient_evidence(product, query))
        sensitivity = self._sensitivity_evidence(scored.product_id, query)
        if sensitivity:
            evidence.append(sensitivity)
        evidence.extend(self._quality_evidence(product))
        budget = self._budget_evidence(product, query)
        if budget:
            evidence.append(budget)

        return evidence

    # ------------------------------------------------------------------

    def _cohort_evidence(self, product_id: str, query: Query) -> Evidence | None:
        """The strongest line available, when the sample supports it.

        Suppressed entirely below `min_cohort` rather than shown with a caveat.
        A percentage from eleven reviewers reads as authoritative no matter what
        hedge is attached to it, so the honest move is not to print it.
        """
        if self.cohort_stats is None or not query.skin_type:
            return None
        try:
            row = self.cohort_stats.loc[(product_id, query.skin_type)]
        except KeyError:
            return None

        n_reviews = int(row["n_reviews"])
        if n_reviews < self.min_cohort:
            return None

        share = int(row["n_positive"]) / n_reviews
        return Evidence(
            label=(
                f"{share:.0%} of {query.skin_type}-skin reviewers "
                f"rated this {POSITIVE_RATING:.0f} or above"
            ),
            supported=share >= 0.5,
            detail=f"based on {n_reviews:,} reviews from {query.skin_type}-skin users",
            kind="evidence",
        )

    def _skin_type_evidence(self, product, query: Query) -> list[Evidence]:
        if not query.skin_type:
            return []
        tagged = list(product[ProductCols.SKIN_TYPES])
        if not tagged:
            return [
                Evidence(
                    label="No skin-type suitability recorded for this product",
                    supported=False,
                    detail="88% of the catalogue is untagged, so this is not a mismatch",
                    kind="caveat",
                )
            ]
        return [
            Evidence(
                label=f"Suitable for {query.skin_type} skin",
                supported=query.skin_type in tagged,
                detail=f"tagged for {', '.join(tagged)}",
                kind="match" if query.skin_type in tagged else "caveat",
            )
        ]

    def _concern_evidence(self, product, query: Query) -> list[Evidence]:
        addressed = set(product[ProductCols.CONCERNS])
        lines = []
        for slug in query.concerns:
            definition = CONCERNS_BY_SLUG.get(slug)
            label = definition.label if definition else slug
            lines.append(
                Evidence(
                    label=f"Addresses {label.lower()}",
                    supported=slug in addressed,
                    detail="from the product's own highlights"
                    if slug in addressed
                    else "not listed among this product's highlights",
                    kind="match" if slug in addressed else "caveat",
                )
            )
        return lines

    def _ingredient_evidence(self, product, query: Query) -> list[Evidence]:
        present = [h for h in product[ProductCols.HIGHLIGHTS] if h in INGREDIENT_HIGHLIGHTS]
        if not present:
            return []
        return [
            Evidence(
                label=f"Contains {', '.join(present)}",
                supported=True,
                detail="listed in the product highlights",
                kind="match",
            )
        ]

    def _sensitivity_evidence(self, product_id: str, query: Query) -> Evidence | None:
        if "sensitivity" not in query.concerns:
            return None
        if product_id not in self._irritants.index:
            return None
        flags = self._irritants.loc[product_id]
        if bool(flags[rules.UNVERIFIABLE]):
            return Evidence(
                label="Could not check for common irritants",
                supported=False,
                detail="no ingredient list published for this product",
                kind="caveat",
            )
        return Evidence(
            label="No fragrance, drying alcohol or harsh sulfates in the ingredients",
            supported=True,
            detail="checked against the full ingredient list",
            kind="match",
        )

    def _quality_evidence(self, product) -> list[Evidence]:
        rating = product.get(ProductCols.RATING)
        n_reviews = product.get(ProductCols.N_REVIEWS)
        if pd.isna(rating):
            return []
        count = 0 if pd.isna(n_reviews) else int(n_reviews)
        return [
            Evidence(
                label=f"Rated {float(rating):.1f} out of 5",
                supported=float(rating) >= POSITIVE_RATING,
                detail=f"from {count:,} reviews" if count else "few reviews so far",
                kind="evidence",
            )
        ]

    def _budget_evidence(self, product, query: Query) -> Evidence | None:
        price = product.get(ProductCols.PRICE)
        if query.budget_max is None or pd.isna(price):
            return None
        return Evidence(
            label=f"${float(price):.0f}, within your ${query.budget_max:.0f} budget",
            supported=float(price) <= query.budget_max,
            detail="",
            kind="match",
        )
